name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'config-example/**'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - staging
          - production
        default: 'staging'
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
    - name: Run Replacer
      working-directory: config-example
      run: go run main.go -key currency -value EUR
    - name: Set instance key
      run: |
        echo "${{ secrets.INSTANCE_KEY }}" > instance.pem
        chmod 400 instance.pem
    - name: Copy files to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: instance.pem
        source: /config-example
        target: /home/ubuntu/config-example