name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'config-example/**'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - stg
          - prod
        default: 'stg'
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22
    - name: Run Search
      id: search
      working-directory: config-example
      run: |
        if [[ -z "${{ github.event.inputs.environment }}" ]]; then
          output=$(go run ./main.go -env stg get-database-host)
          echo "::set-output name=database-host::$output"
        else
          output=$(go run ./main.go -env ${{ github.event.inputs.environment }} get-database-host)
          echo "::set-output name=database-host::$output"
        fi
    - name: Run Replacer
      working-directory: config-example
      run: go run main.go -key database -value ${{ steps.search.outputs.database-host }} replace
    - name: Set instance key
      run: |
        echo "${{ secrets.INSTANCE_KEY }}" > instance.pem
        chmod 400 instance.pem
    - name: Copy files to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: instance.pem
        source: config-example/*
        target: /home/ubuntu/config-example