name: init-test

on:
  push:
    branches:
      - main

jobs:
  print-hello-worlds:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
  
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Navigate to go-test
        run: cd go-test
      - name: List files
        run: ls -la
      - name: Build Go
        run: go build
      - name: Run Go
        run: ./ekky-gotest