name: init-test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'
  push:
    branches:
      - main

jobs:
  print-hello-worlds:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello ${{ github.event.inputs.name }}!"
  
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Run Go
        run: go run ./main.go
        working-directory: ./go-test